config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :news, as: 'admin_news'

    resources :subjects, as: 'admin_subjects', only: [:new, :create, :edit, :update, :destroy]
    resources :majors, as: 'admin_majors', only: [:new, :create, :edit, :update, :destroy]
    resources :company_types, as: 'admin_company_types', only: [:new, :create, :edit, :update, :destroy]
    resources :company_scales, as: 'admin_company_scales', only: [:new, :create, :edit, :update, :destroy]
    resources :post_types, as: 'admin_post_types', only: [:new, :create, :edit, :update, :destroy]
    resources :post_sub_types, as: 'admin_post_sub_types', only: [:new, :create, :edit, :update, :destroy]
  end

  scope 'company' do
    resources :delivers, only: [:destroy]

    resources :assets, as: 'company_assets', :controller => 'company/assets', :except => [:show] do
      member do
        get 'download'
      end
    end

    resources :posts, as: 'company_posts' do
      resources :requirements, only: :destroy
    end
  end

  scope 'student' do
    resources :assets, as: 'student_assets', :controller => 'student/assets', :except => [:show] do
      member do
        get 'download'
      end
    end

    resources :resumes, as: 'student_resumes' do
      resources :educations, :glories, :interests, :sample_works, :skills, :work_experiences, only: :destroy
    end
  end

  devise_for :admins
  devise_for :companies
  devise_for :students

  root 'home#index'

  match '/introduce', to: 'home#introduce', via: 'get'
  match '/contact', to: 'home#contact', via: 'get'

  match '/student', to: 'student#index', via: 'get'
  match '/admin', to: 'admin#index', via: 'get'
  match '/company', to: 'company#index', via: 'get'

  get '/student/information' => 'student#information'
  get '/student/search_post' => 'student#search_post'
  get '/student/browse_post/:id' => 'student#browse_post'
  get '/student/browse_news/:id' => 'student#browse_news'
  get '/student/browse_company/:id' => 'student#browse_company'
  patch '/student/commit_for_update' => 'student#commit_for_update'
  post '/student/deliver' => 'student#deliver_to_post'

  get '/company/information' => 'company#information'
  get '/company/search_resume' => 'company#search_resume'
  get '/company/browse_resume/:id' => 'company#browse_resume'
  get '/company/browse_news/:id' => 'company#browse_news'
  get '/company/browse_student/:id' => 'company#browse_student'
  patch '/company/commit_for_update' => 'company#commit_for_update'

  get '/admin/settings' => 'admin#settings'
  post '/admin/import_student_accounts' => 'admin#import_student_accounts'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :student
  belongs_to :company
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :resume
  belongs_to :post

  has_many :replies, class_name: "Comment", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Comment"
end

app/models/company.rb
class Company < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable

  has_many :posts, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :delivers, through: :posts

end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
  belongs_to :post
  belongs_to :resume

  validates :post_id, :resume_id, presence: true

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :resume
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/glory.rb
class Glory < ActiveRecord::Base
  belongs_to :resume
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :resume
end

app/models/major.rb
class Major < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :company

  has_many :requirements, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :delivers, dependent: :destroy

  accepts_nested_attributes_for :requirements, :reject_if => :all_blank, :allow_destroy => true
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to :post
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :student

  has_many :educations, dependent: :destroy
  has_many :glories, dependent: :destroy
  has_many :interests, dependent: :destroy
  has_many :sample_works, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :work_experiences, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :delivers, dependent: :destroy

  accepts_nested_attributes_for :comments, :educations, :glories, :interests, :sample_works, :skills, :work_experiences,
                                :reject_if => :all_blank, :allow_destroy => true

  validates :title, presence: true
end

app/models/sample_work.rb
class SampleWork < ActiveRecord::Base
  belongs_to :resume
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :resume
end

app/models/student.rb
class Student < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable

  has_many :resumes, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :delivers, through: :resumes

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/views/admin/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '首页', admin_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'admin/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if admin_signed_in? %>
    <li><%= link_to '新闻广播', admin_news_index_path %></li>
    <li><%= link_to '设置', admin_settings_path %></li>
    <li><%= link_to '我的帐户', edit_admin_registration_path %></li>
<% end %>

<% if admin_signed_in? %>
  <li><%= link_to '登出', destroy_admin_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to '登录', new_admin_session_path %></li>
<% end %>

app/views/admin/index.html.erb
<div class="panel panel-info admin-panel-info">
  <div class="panel-heading">导入学生帐户</div>
  <div class="panel-body">用于将统计后的学生数据(excel表格)导入</div>

  <%= form_for(current_admin, url: '/admin/import_student_accounts', method: 'post',
               html: {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-2">
          <%= f.file_field :student_infos, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
          <button type="submit" class="btn btn-default">提交</button>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/settings.html.erb
<div class="panel panel-info admin-panel-info admin-panel-subject">
  <div class="panel-heading">学院</div>
  <div class="panel-body">
    <%= link_to "添加", new_admin_subject_path %>
  </div>

  <%= render 'subjects/table' %>
</div>

<div class="panel panel-info admin-panel-info admin-panel-major">
  <div class="panel-heading">专业</div>

  <div class="panel-body">
    <%= link_to "添加", new_admin_major_path %>
  </div>

  <%= render 'majors/table' %>
</div>

<div class="panel panel-info admin-panel-info admin-panel-company-type">
  <div class="panel-heading">公司类型</div>

  <div class="panel-body">
    <%= link_to "添加", new_admin_company_type_path %>
  </div>

  <%= render 'company_types/table' %>
</div>

<div class="panel panel-info admin-panel-info admin-panel-company-scale">
  <div class="panel-heading">公司规模</div>

  <div class="panel-body">
    <%= link_to "添加", new_admin_company_scale_path %>
  </div>

  <%= render 'company_scales/table' %>
</div>

<div class="panel panel-info admin-panel-info admin-panel-post-type">
  <div class="panel-heading">行业类型</div>

  <div class="panel-body">
    <%= link_to "添加", new_admin_post_type_path %>
  </div>

  <%= render 'post_types/table' %>
</div>

<div class="panel panel-info admin-panel-info admin-panel-post-sub-type">
  <div class="panel-heading">职位细分</div>

  <div class="panel-body">
    <%= link_to "添加", new_admin_post_sub_type_path %>
  </div>

  <%= render 'post_sub_types/table' %>
</div>