config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :news, as: 'admin_news'

    resources :subjects, as: 'admin_subjects', only: [:new, :create, :edit, :update, :destroy]
    resources :majors, as: 'admin_majors', only: [:new, :create, :edit, :update, :destroy]
    resources :company_types, as: 'admin_company_types', only: [:new, :create, :edit, :update, :destroy]
    resources :company_scales, as: 'admin_company_scales', only: [:new, :create, :edit, :update, :destroy]
    resources :post_types, as: 'admin_post_types', only: [:new, :create, :edit, :update, :destroy]
    resources :post_sub_types, as: 'admin_post_sub_types', only: [:new, :create, :edit, :update, :destroy]
  end

  scope 'company' do
    resources :delivers, only: [:destroy]

    resources :assets, as: 'company_assets', :controller => 'company/assets', :except => [:show] do
      member do
        get 'download'
      end
    end

    resources :posts, as: 'company_posts' do
      resources :requirements, only: :destroy
    end
  end

  scope 'student' do
    resources :assets, as: 'student_assets', :controller => 'student/assets', :except => [:show] do
      member do
        get 'download'
      end
    end

    resources :resumes, as: 'student_resumes' do
      resources :educations, :glories, :interests, :sample_works, :skills, :work_experiences, only: :destroy
    end
  end

  devise_for :admins
  devise_for :companies
  devise_for :students

  root 'home#index'

  match '/introduce', to: 'home#introduce', via: 'get'
  match '/contact', to: 'home#contact', via: 'get'

  match '/student', to: 'student#index', via: 'get'
  match '/admin', to: 'admin#index', via: 'get'
  match '/company', to: 'company#index', via: 'get'

  get '/student/information' => 'student#information'
  get '/student/search_post' => 'student#search_post'
  get '/student/browse_post/:id' => 'student#browse_post'
  get '/student/browse_news/:id' => 'student#browse_news'
  get '/student/browse_company/:id' => 'student#browse_company'
  patch '/student/commit_for_update' => 'student#commit_for_update'
  post '/student/deliver' => 'student#deliver_to_post'

  get '/company/information' => 'company#information'
  get '/company/search_resume' => 'company#search_resume'
  get '/company/browse_resume/:id' => 'company#browse_resume'
  get '/company/browse_news/:id' => 'company#browse_news'
  get '/company/browse_student/:id' => 'company#browse_student'
  patch '/company/commit_for_update' => 'company#commit_for_update'

  get '/admin/settings' => 'admin#settings'
  post '/admin/import_student_accounts' => 'admin#import_student_accounts'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :student
  belongs_to :company
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :resume
  belongs_to :post

  has_many :replies, class_name: "Comment", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Comment"
end

app/models/company.rb
class Company < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable

  has_many :posts, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :delivers, through: :posts

end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
  belongs_to :post
  belongs_to :resume

  validates :post_id, :resume_id, presence: true

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :resume
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/glory.rb
class Glory < ActiveRecord::Base
  belongs_to :resume
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :resume
end

app/models/major.rb
class Major < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :company

  has_many :requirements, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :delivers, dependent: :destroy

  accepts_nested_attributes_for :requirements, :reject_if => :all_blank, :allow_destroy => true
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to :post
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :student

  has_many :educations, dependent: :destroy
  has_many :glories, dependent: :destroy
  has_many :interests, dependent: :destroy
  has_many :sample_works, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :work_experiences, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :delivers, dependent: :destroy

  accepts_nested_attributes_for :comments, :educations, :glories, :interests, :sample_works, :skills, :work_experiences,
                                :reject_if => :all_blank, :allow_destroy => true

  validates :title, presence: true
end

app/models/sample_work.rb
class SampleWork < ActiveRecord::Base
  belongs_to :resume
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :resume
end

app/models/student.rb
class Student < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable

  has_many :resumes, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :delivers, through: :resumes

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :ensure_variables

  layout 'student'

  def index
    @resumes = @resumes.order("updated_at DESC").paginate(:page => params[:page])
  end

  def show
    @resume = @resumes.find(params[:id])
  end

  def new
    @resume = Resume.new
    build_sub_attrs
  end

  def create
    @resume = @resumes.create(resume_params)
    if @resume.save
      redirect_to student_resumes_path
    else
      redirect_to new_student_resume_path
    end
  end

  def edit
    @resume = @resumes.find(params[:id])

    build_sub_attrs
  end

  def update
    @resume = @resumes.find(params[:id])
    @resume.update(resume_params)

    redirect_to student_resumes_path
  end

  def destroy
    @resume = @resumes.find(params[:id])
    @resume.destroy

    redirect_to student_resumes_path
  end

  private

  def resume_params
    params.require(:resume).permit!
  end

  def ensure_variables
    @student = current_student
    @resumes = @student.resumes
  end

  def build_sub_attrs
    @resume = @resume || Resume.new

    @resume.educations.build
    @resume.glories.build
    @resume.interests.build
    @resume.skills.build
    @resume.sample_works.build
    @resume.work_experiences.build
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_comment.html.erb
<div class="comment-box">
  <h4>评论列表</h4>

  <div class="comment-list">
    <div class="container">
      <% @resume.comments.each do |comment| %>
          <div class="row">
            <div class="col-lg-1 comment-profile"><%= image_tag "profile.jpg" %></div>
            <div class="col-lg-8">
              <h4><%= comment.title %></h4>
              <p><%= comment.content %></p>
              <div>
                <span><%= comment.created_at %></span>
                <span><%= link_to '回复', '#' %></span>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resumes/_education.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-1">
    <% if education_counter == 0 %>
        <h5>教育经历</h5>
    <% end %>
  </div>

  <div class="col-lg-6">
    <p>
      <t><%= education.degree %></t>
      <br/>
      <%= education.school_name %>
    </p>
  </div>

  <div class="col-lg-3">
    <p>
      <sm><%= education.start_date %> ~ <%= education.end_date %></sm>
      <br/>
      <% if education.end_date > Date.today %>
          <imp>
            <sm>正在就读</sm>
          </imp>
      <% end %>
    </p>
  </div>
</div>

app/views/resumes/_form.html.erb
<div class="form-group">
  <%= label_tag :resume_title, "简历名称：", class: "col-sm-1 control-label" %>
  <div class="col-sm-2">
    <%= form.text_field :title, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= label_tag :resume_introduce, "介绍：", class: "col-sm-1 control-label" %>
  <div class="col-sm-8">
    <%= form.text_area :introduce, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= label_tag :educations, "教育经历：", class: "col-sm-1 control-label" %>

  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-education-field">
      添加教育经历
    </button>
  </div>
</div>

<%= form.fields_for :educations do |builder| %>
    <%= render "resumes/education_fields", :f => builder %>
<% end %>


<div class="form-group">
  <%= label_tag :glories, "获奖情况：", class: "col-sm-1 control-label" %>

  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-glory-field">
      添加奖项
    </button>
  </div>
</div>

<%= form.fields_for :glories do |builder| %>
    <%= render "resumes/glory_fields", :f => builder %>
<% end %>


<div class="form-group">
  <%= label_tag :work_experiences, "工作经历：", class: "col-sm-1 control-label" %>

  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-work-experience-field">
      添加工作经历
    </button>
  </div>
</div>

<%= form.fields_for :work_experiences do |builder| %>
    <%= render "resumes/work_experience_fields", :f => builder %>
<% end %>

<div class="form-group">
  <%= label_tag :skills, "技能：", class: "col-sm-1 control-label" %>
  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-skill-field">
      添加技能
    </button>
  </div>
</div>

<%= form.fields_for :skills do |builder| %>
    <%= render "resumes/skill_fields", :f => builder %>
<% end %>

<div class="form-group">
  <%= label_tag :sample_works, "作品样例：", class: "col-sm-1 control-label" %>
  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-sample-work-field">
      添加作品项目
    </button>
  </div>
</div>

<%= form.fields_for :sample_works do |builder| %>
    <%= render "resumes/sample_work_fields", :f => builder %>
<% end %>

<div class="form-group">
  <%= label_tag :interests, "兴趣爱好：", class: "col-sm-1 control-label" %>
  <div class="col-sm-2">
    <button type="button" id="resume-add-button" class="btn btn-primary glyphicon glyphicon-plus add-nested-interest-field">
      添加兴趣
    </button>
  </div>
</div>

<%= form.fields_for :interests do |builder| %>
    <%= render "resumes/interest_fields", :f => builder %>
<% end %>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <button type="submit" class="btn btn-default">创建</button>
  </div>
</div>

app/views/resumes/_glory.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-1">
    <% if glory_counter == 0 %>
        <h5>获奖</h5>
    <% end %>
  </div>

  <div class="col-lg-6">
    <p>
      <t><%= glory.title %></t>
      <br/>

    </p>

    <p>
      <more>
        <%= glory.description %>
      </more>
    </p>
  </div>

  <div class="col-lg-3">
    <p>
      <sm><%= glory.date %></sm>
    </p>
  </div>
</div>

app/views/resumes/_glory_fields.html.erb
<div class="form-group nested-glory-field">
  <div class="col-sm-1 control-label"></div>
  <div class="col-sm-8 resume-group">
    <div class="col-sm-2">
      <%= f.text_field :date, class: "form-control  datepicker",
                       :placeholder => "获奖日期" %>
    </div>

    <div class="col-sm-4">
      <%= f.text_field :title, class: "form-control",
                       :placeholder => "奖项名称" %>
    </div>

    <div class="col-sm-6">
      <%= f.text_area :description, class: "form-control",
                      :placeholder => "描述" %>
    </div>
  </div>

  <div class="col-sm-1">
    <% if f.object.new_record? %>
        <button type="button" class='destroy-nested-form btn-danger form-control destroy-nested-glory-field'>删除</button>
    <% else %>
        <%= link_to '删除', student_resume_glory_path(@resume, f.object), :remote => true, :method => :delete,
                    class: 'destroy-nested-form btn-danger form-control destroy-nested-glory-field' %>
    <% end %>
  </div>

</div>

app/views/resumes/_interest.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-1">
    <% if interest_counter == 0 %>
        <h5>兴趣爱好</h5>
    <% end %>
  </div>

  <div class="col-lg-6">
    <p>
      <t class="glyphicon glyphicon-heart">  <%= interest.title %></t>
      <br/>
      <%= interest.detail %>
    </p>
  </div>
</div>

app/views/resumes/_resume.html.erb
<!-- header wrap -->
<div id="headerwrap">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-12">
        <h2><%= @resume.student.name %></h2>
        <h5><%= @resume.student.age %>岁 | <%= @resume.title %></h5>
        <br/>
        <h5><%= @resume.updated_at %></h5>
      </div>
    </div>
  </div>
</div>

<!--  introduce section-->
<div id="intro">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-lg-offset-1">
        <h5>关于</h5>
      </div>

      <div class="col-lg-6"><p><%= @resume.introduce %></p></div>
    </div>
  </div>
</div>

<!--  education section-->
<% if @resume.educations.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/education', collection: @resume.educations %>
      <hr/>
    </div>
<% end %>

<!--  work experience section-->
<% if @resume.work_experiences.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/work_experience', collection: @resume.work_experiences %>
      <hr/>
    </div>
<% end %>

<!--  glory section-->
<% if @resume.glories.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/glory', collection: @resume.glories %>

      <hr/>
    </div>
<% end %>

<!--  skill section-->
<% if @resume.skills.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/skill', collection: @resume.skills %>

      <hr/>
    </div>
<% end %>

<!--  sample work section-->
<% if @resume.sample_works.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/sample_work', collection: @resume.sample_works %>
      <hr/>
    </div>
<% end %>

<!--  interest section-->
<% if @resume.interests.length > 0 %>
    <div class="container desc">
      <%= render partial: 'resumes/interest', collection: @resume.interests %>
    </div>
<% end %>

<div id="footwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-lg-offset-1"><h5>联系方式</h5></div>
      <div class="col-lg-6">
        <p>
          <t>邮箱</t>
          <br/>
          <%= @student.email %>
        </p>

        <p>
          <t>地址</t>
          <br/>
          <%= @student.address %>
        </p>

        <p>
          <t>电话</t>
          <br/>
          <%= @student.telephone %>
        </p>
      </div>
      <div class="col-lg-3">
        <p>
          <sm>社交</sm>
        </p>

        <p>QQ: <%= @student.tencent_qq %></p>
      </div>
    </div>
  </div>
</div>

app/views/resumes/_sample_work_fields.html.erb
<div class="form-group nested-sample-work-field">
  <div class="col-sm-1 control-label"></div>
  <div class="col-sm-8 resume-group">
    <div class="col-sm-2">
      <%= f.text_field :title, class: "form-control",
                       :placeholder => "项目名" %>
    </div>

    <div class="col-sm-4">
      <%= f.text_field :description, class: "form-control",
                       :placeholder => "描述" %>
    </div>

    <div class="col-sm-4">
      <%= f.text_field :demo_url, class: "form-control",
                       :placeholder => "演示地址" %>
    </div>
  </div>

  <div class="col-sm-1">
    <% if f.object.new_record? %>
        <button type="button" class='destroy-nested-form btn-danger form-control destroy-nested-sample-work-field'>删除</button>
    <% else %>
        <%= link_to '删除', student_resume_sample_work_path(@resume, f.object), :remote => true, :method => :delete,
                    class: 'destroy-nested-form btn-danger form-control destroy-nested-sample-work-field' %>
    <% end %>
  </div>
</div>

app/views/resumes/_skill.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-1">
    <% if skill_counter == 0 %>
        <h5>技能</h5>
    <% end %>
  </div>

  <div class="col-lg-6">
    <p>
      <t class="glyphicon glyphicon-ok">  <%= skill.title %></t>
      <br/>
      <%= skill.detail %>
    </p>
  </div>
</div>

app/views/resumes/_skill_fields.html.erb
<div class="form-group nested-skill-field">
  <div class="col-sm-1 control-label"></div>
  <div class="col-sm-8 resume-group">
    <div class="col-sm-2">
      <%= f.text_field :title, class: "form-control",
                       :placeholder => "技能名称" %>
    </div>

    <div class="col-sm-4">
      <%= f.text_field :detail, class: "form-control",
                       :placeholder => "技能描述" %>
    </div>
  </div>

  <div class="col-sm-1">
    <% if f.object.new_record? %>
        <button type="button" class='destroy-nested-form btn-danger form-control destroy-nested-skill-field'>删除</button>
    <% else %>
        <%= link_to '删除', student_resume_skill_path(@resume, f.object), :remote => true, :method => :delete,
                    class: 'destroy-nested-form btn-danger form-control destroy-nested-skill-field' %>
    <% end %>
  </div>
</div>

app/views/resumes/_work_experience.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-1">
    <% if work_experience_counter == 0 %>
        <h5>工作经历</h5>
    <% end %>
  </div>

  <div class="col-lg-6">
    <p>
      <t><%= work_experience.appointment %></t>
      <br/>
      <%= work_experience.company_name %>
    </p>

    <p>
      <more><%= work_experience.description %></more>
    </p>
  </div>

  <div class="col-lg-3">
    <p>
      <sm><%= work_experience.start_date %> ~ <%= work_experience.end_date %></sm>
      <br/>
    </p>
  </div>
</div>

app/views/resumes/_work_experience_fields.html.erb
<div class="form-group nested-work-experience-field">
  <div class="col-sm-1 control-label"></div>
  <div class="col-sm-8 resume-group">
    <div class="col-sm-2">
      <%= f.text_field :start_date, class: "form-control  datepicker",
                       :placeholder => "起始日期" %>
    </div>

    <div class="col-sm-2">
      <%= f.text_field :end_date, class: "form-control  datepicker",
                       :placeholder => "结束日期" %>
    </div>

    <div class="col-sm-2">
      <%= f.text_field :company_name, class: "form-control",
                       :placeholder => "公司名" %>
    </div>

    <div class="col-sm-2">
      <%= f.text_field :appointment, class: "form-control",
                       :placeholder => "职位" %>
    </div>

    <div class="col-sm-2">
      <%= f.text_field :duty, class: "form-control",
                       :placeholder => "职责" %>
    </div>

    <div class="col-sm-2">
      <%= f.text_field :description, class: "form-control",
                       :placeholder => "职责描述" %>
    </div>

  </div>

  <div class="col-sm-1">
    <% if f.object.new_record? %>
        <button type="button" class='destroy-nested-form btn-danger form-control destroy-nested-work-experience-field'>删除</button>
    <% else %>
        <%= link_to '删除', student_resume_work_experience_path(@resume, f.object), :remote => true, :method => :delete,
                    class: 'destroy-nested-form btn-danger form-control destroy-nested-work-experience-field' %>
    <% end %>
  </div>
</div>

app/views/resumes/edit.html.erb
<div class="panel panel-info student-panel-info">
  <div class="panel-heading">编辑简历</div>

  <div class="panel-body"></div>

  <%= form_for([@student, @resume],
               url: student_resume_path(@resume),
               html: {class: 'form-horizontal', role: 'form'}) do |f| %>
      <%= render partial: "resumes/form", locals: {form: f} %>
  <% end %>

</div>

app/views/resumes/new.html.erb
<div class="panel panel-info student-panel-info">
  <div class="panel-heading">新简历</div>

  <div class="panel-body"></div>

  <%= form_for([@student, @resume],
               html: {class: 'form-horizontal', role: 'form'}) do |f| %>
      <%= render partial: "resumes/form", locals: {form: f} %>
  <% end %>

</div>